"""Model-comparison reports generated by ``make train``.

``reports/model_comparison.json`` is the single source of truth for model
metrics; the markdown report and the README results table are rendered from it
so documentation can never drift from the actual training run.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

README_START = "<!-- model-comparison:start -->"
README_END = "<!-- model-comparison:end -->"


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def write_json_report(report: dict[str, Any], path: Path) -> Path:
    """Write the comparison report as pretty JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
    return path


def results_table(report: dict[str, Any]) -> str:
    """Markdown table: one row per candidate (CV, holdout and gate-set metrics)."""
    selected = report["selected_model"]
    lines = [
        "| Model | CV ROC-AUC (mean ± std) | Holdout ROC-AUC | Holdout PR-AUC | Holdout F1 | Holdout Recall "
        "| Holdout expected loss | Normal-stream ROC-AUC | Normal-stream expected loss |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for model in report["models"]:
        cv, holdout, gate = model["cv"], model["holdout"], model["normal_stream"]
        name = f"**{model['display_name']}** (selected)" if model["name"] == selected else model["display_name"]
        lines.append(
            f"| {name} | {_fmt(cv['roc_auc_mean'])} ± {_fmt(cv['roc_auc_std'])} | {_fmt(holdout['roc_auc'])} "
            f"| {_fmt(holdout['pr_auc'])} | {_fmt(holdout['f1_score'])} | {_fmt(holdout['recall'])} "
            f"| {_fmt(holdout['expected_loss'])} | {_fmt(gate['roc_auc'])} | {_fmt(gate['expected_loss'])} |"
        )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    """Full markdown report (Vietnamese prose, English technical terms)."""
    cfg = report["config"]
    gate = report["gate"]
    registry = report.get("registry") or {}
    data = report["data"]
    selected = next(m for m in report["models"] if m["name"] == report["selected_model"])
    decision = "PROMOTE" if gate["promote"] else "GIỮ CHAMPION HIỆN TẠI"

    params = "\n".join(f"| `{key}` | `{value}` |" for key, value in sorted(selected["best_params"].items()))
    reasons = "\n".join(f"- {reason}" for reason in gate["reasons"])
    tuning_rows = "\n".join(
        f"| {m['display_name']} | {m['tuning']['n_trials']} | {m['tuning']['n_pruned']} "
        f"| {_fmt(m['tuning']['duration_seconds'], 1)} | {m['tuning']['best_trial']} "
        f"| {_fmt(m['cv']['cost_optimal_threshold'], 2)} | `{m.get('mlflow_run_id') or '—'}` |"
        for m in report["models"]
    )
    champion_line = (
        f"`{registry.get('model_name')}` version **{registry.get('registered_version')}**; "
        f"`@champion` = version **{registry.get('champion_version')}**"
        if registry.get("registered_version")
        else "MLflow không khả dụng — chỉ lưu artifact local."
    )
    train_line = (
        f"`{data['train_file']}` — {data['train_rows']} dòng train + {data['holdout_rows']} dòng holdout "
        f"(stratified {cfg['test_size']:.0%})"
    )
    hpo_line = (
        f"Optuna TPE (seed {cfg['random_state']}) + MedianPruner, {cfg['n_trials']} trial/model, "
        f"objective CV `{cfg['metric']}`"
    )
    cost_line = (
        f"FN = {cfg['cost_false_negative']}, FP = {cfg['cost_false_positive']} "
        "(expected loss = tổng loss / số khách hàng)"
    )

    return f"""# Báo cáo so sánh model

> Sinh tự động bởi `make train` ({report['generated_at']}, session `{report['session_id']}`).
> Không sửa tay — số liệu trong README/docs được render từ `reports/model_comparison.json`.

## Thiết lập

| Mục | Giá trị |
|---|---|
| Dữ liệu train | {train_line} |
| Tập gate champion/challenger | `{data['gate_file']}` — {data['gate_rows']} dòng, không dùng để train |
| Data version (manifest fingerprint) | `{data['data_version']}` (manifest khớp file: {data['manifest_verified']}) |
| Cross-validation | StratifiedKFold {cfg['cv_folds']} fold, `random_state={cfg['random_state']}` |
| HPO | {hpo_line} |
| Decision threshold | {cfg['decision_threshold']} |
| Cost matrix | {cost_line} |
| Feature | 23 feature gốc + {cfg['n_engineered_features']} feature engineered |

## Kết quả

{results_table(report)}

## Model được chọn: {selected['display_name']}

Chọn theo CV `{cfg['metric']}` cao nhất. Hyper-parameter tốt nhất:

| Param | Giá trị |
|---|---|
{params}

## Champion/challenger gate — {decision}

{reasons}

Registry: {champion_line}

## Chi tiết HPO

| Model | Trials | Pruned | Thời gian (s) | Best trial | Cost-optimal threshold (OOF) | MLflow run |
|---|---|---|---|---|---|---|
{tuning_rows}

## Hình minh hoạ

- ROC holdout tất cả model: `reports/figures/roc_comparison.png`
- PR holdout tất cả model: `reports/figures/pr_comparison.png`
- Confusion matrix model được chọn: `reports/figures/confusion_matrix_selected.png`
- Feature importance model được chọn: `reports/figures/feature_importance_selected.png`
"""


def write_markdown_report(report: dict[str, Any], path: Path) -> Path:
    """Render and write the markdown report."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(report), encoding="utf-8")
    return path


def sync_readme(report: dict[str, Any], readme_path: Path) -> bool:
    """Replace the block between the README markers with the current results table.

    Returns:
        ``True`` when the README contained the markers and was updated.
    """
    if not readme_path.exists():
        return False
    content = readme_path.read_text(encoding="utf-8")
    if README_START not in content or README_END not in content:
        return False
    selected = next(m for m in report["models"] if m["name"] == report["selected_model"])
    gate = "promote" if report["gate"]["promote"] else "giữ champion hiện tại"
    block = (
        f"{README_START}\n"
        f"_Sinh tự động từ `reports/model_comparison.json` (session `{report['session_id']}`)._\n\n"
        f"{results_table(report)}\n\n"
        f"Model được chọn: **{selected['display_name']}** — gate: **{gate}**. "
        f"Chi tiết: [`reports/model_comparison.md`](reports/model_comparison.md).\n"
        f"{README_END}"
    )
    pattern = re.compile(re.escape(README_START) + r".*?" + re.escape(README_END), re.DOTALL)
    readme_path.write_text(pattern.sub(lambda _: block, content), encoding="utf-8")
    return True
