"""Export the scoring API's OpenAPI document to docs/openapi.yaml (``make openapi``).

Runs hermetically (APP_ENV=test): no MLflow, database or network is needed
because the document is generated from the route and schema definitions.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))
os.environ["APP_ENV"] = "test"

import yaml  # noqa: E402

from credit_risk.serving.app import create_app  # noqa: E402


def main(output: Path) -> None:
    spec = create_app().openapi()
    output.parent.mkdir(parents=True, exist_ok=True)
    header = "# Generated by scripts/export_openapi.py — do not edit by hand (run `make openapi`).\n"
    output.write_text(header + yaml.safe_dump(spec, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"Wrote {output.relative_to(PROJECT_ROOT)} ({len(spec['paths'])} paths)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=PROJECT_ROOT / "docs" / "openapi.yaml")
    main(parser.parse_args().output)
